# Generated by Django 5.2.5 on 2025-09-07 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ランク')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('mentee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relation', to=settings.AUTH_USER_MODEL, verbose_name='弟子')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to=settings.AUTH_USER_MODEL, verbose_name='師匠')),
            ],
            options={
                'verbose_name': '師弟関係',
                'verbose_name_plural': '師弟関係',
            },
        ),
        migrations.CreateModel(
            name='MentorRelationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '拒否済み')], default='pending', max_length=10, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='申請元ユーザー')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='申請先ユーザー')),
            ],
            options={
                'verbose_name': '師弟関係リクエスト',
                'verbose_name_plural': '師弟関係リクエスト',
            },
        ),
    ]
