# Generated by Django 5.2.5 on 2025-09-10 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentorship', '0001_initial'),
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorrelation',
            name='mentee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relation', to=settings.AUTH_USER_MODEL, verbose_name='弟子'),
        ),
        migrations.AddField(
            model_name='mentorrelation',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to=settings.AUTH_USER_MODEL, verbose_name='師匠'),
        ),
        migrations.AddField(
            model_name='mentorrelation',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_relations', to='topics.topic', verbose_name='トピック'),
        ),
        migrations.AddField(
            model_name='mentorrelationrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='申請元ユーザー'),
        ),
        migrations.AddField(
            model_name='mentorrelationrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='申請先ユーザー'),
        ),
        migrations.AddField(
            model_name='mentorrelationrequest',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to='topics.topic', verbose_name='トピック'),
        ),
    ]
