# Generated by Django 5.2.5 on 2025-09-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorrelation',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_relations', to='topics.topic', verbose_name='トピック'),
        ),
        migrations.AddField(
            model_name='mentorrelationrequest',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to='topics.topic', verbose_name='トピック'),
        ),
    ]
