# Generated by Django 5.2.5 on 2025-09-09 06:13

from django.db import migrations


def populate_topic_field(apps, schema_editor):
    MentorRelationRequest = apps.get_model('mentorship', 'MentorRelationRequest')
    MentorRelation = apps.get_model('mentorship', 'MentorRelation')
    Topic = apps.get_model('topics', 'Topic')

    # Get or create a default topic
    default_topic, created = Topic.objects.get_or_create(
        title="General",
        defaults={'description': "General mentorship topic"}
    )

    for obj in MentorRelationRequest.objects.all():
        if obj.topic is None: # Only update if topic is null
            obj.topic = default_topic
            obj.save()

    for obj in MentorRelation.objects.all():
        if obj.topic is None: # Only update if topic is null
            obj.topic = default_topic
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_add_topic_to_mentorship_models'),
    ]

    operations = [
        migrations.RunPython(populate_topic_field),
    ]
