# Generated by Django 5.2.5 on 2025-09-09 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0004_actionlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentorrelation",
            name="rank",
        ),
    ]
