# Generated by Django 5.2.5 on 2025-09-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopic',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'アクティブ'), ('GRADUATED', '卒業済み'), ('EXPELLED', '破門済み')], default='ACTIVE', max_length=20, verbose_name='ステータス'),
        ),
    ]
