# Generated by Django 5.2.5 on 2025-09-10 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='topic',
            name='users',
            field=models.ManyToManyField(related_name='topics', through='topics.UserTopic', to=settings.AUTH_USER_MODEL, verbose_name='関連ユーザー'),
        ),
        migrations.AlterUniqueTogether(
            name='usertopic',
            unique_together={('user', 'topic')},
        ),
    ]
