# Generated by Django 5.2.5 on 2025-09-09 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_users'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # 1. UserTopicモデルを作成
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='レベル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='参加日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic', verbose_name='トピック')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー-トピック関連',
                'verbose_name_plural': 'ユーザー-トピック関連',
            },
        ),
        # 2. unique_together制約を追加
        migrations.AlterUniqueTogether(
            name='usertopic',
            unique_together={('user', 'topic')},
        ),
    ]
