# Generated by Django 5.2.5 on 2025-09-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_usertopic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopic',
            name='mentee_capacity',
            field=models.IntegerField(default=3, verbose_name='弟子定員'),
        ),
    ]
