# Generated by Django 5.2.6 on 2025-09-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_usertopic_mentee_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertopic',
            name='mentee_capacity',
            field=models.IntegerField(default=5, verbose_name='弟子定員'),
        ),
    ]
