# Generated by Django 5.2.5 on 2025-09-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20250909_0543'),
    ]

    operations = [
        # 既存のManyToManyFieldを削除
        migrations.RemoveField(
            model_name='topic',
            name='users',
        ),
        # 新しいthroughパラメータ付きのManyToManyFieldを追加
        migrations.AddField(
            model_name='topic',
            name='users',
            field=models.ManyToManyField(related_name='topics', through='topics.UserTopic', to='auth.user', verbose_name='関連ユーザー'),
        ),
    ]
