# Generated by Django 5.2.6 on 2025-09-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_alter_usertopic_mentee_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopic',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終アクセス日時'),
        ),
    ]
