# Generated by Django 5.2.6 on 2025-09-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_usertopic_last_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='説明'),
        ),
    ]
