# Generated by Django 5.2.5 on 2025-09-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_post', to='threads.thread', verbose_name='元会話スレッド'),
        ),
    ]
