# Generated by Django 5.2.5 on 2025-09-14 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentored_threads', to=settings.AUTH_USER_MODEL, verbose_name='メンター'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_threads', to=settings.AUTH_USER_MODEL, verbose_name='スレッド開始者'),
        ),
    ]
