# Generated by Django 5.2.6 on 2025-09-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_alter_thread_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(default='無題のスレッド', max_length=200, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='threadmessage',
            name='content',
            field=models.TextField(max_length=200, verbose_name='メッセージ内容'),
        ),
    ]
