name: CI for Backend 

on:
    push:
        branches: [ main ]
        paths:
            - 'backend/**'
    pull_request:
        paths:
            - 'backend/**'

jobs:
    test:
        name: Run Django Tests
        runs-on: ubuntu-latest

        env:
            POSTGRES_USER: ${{ vars.POSTGRES_USER_CI }}
            POSTGRES_DB: ${{ vars.POSTGRES_DB_CI }}
            POSTGRES_HOST: 'db'
            POSTGRES_PORT: 5432
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_CI }}

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Build and start containers
          run: docker compose -f backend/compose.yml up -d --build

        - name: Wait for DB to be healthy
          run: |
            echo "⏳ Waiting for database to be ready..."
            for i in {1..15}; do
                if docker container inspect -f '{{.State.Health.Status}}' backend-db-1 | grep -q 'healthy'; then
                    echo "✅ Database is healthy!"
                    exit 0
                fi
                sleep 3
            done
            echo "❌ Database did not become healthy in time."
            docker compose -f backend/compose.yml logs db
            exit 1

        - name: Run Django tests
          run: docker compose -f backend/compose.yml exec -T api python manage.py test

        - name: Stop and remove containers
          if: always()
          run: docker compose -f backend/compose.yml down
